use_frameworks!

platform :ios, '9.0'

target 'HunteronTool_Example' do
  pod 'HunteronTool', :path => '../'

  target 'HunteronTool_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
